### PR TITLE
Add ToSimpleWithChildren()

### PR DESCRIPTION
**Pull request by blackboxlogic**
Resolves https://github.com/OsmSharp/core/issues/102

### CODE REVIEW

**Comment by juliusfriedman** [comment]
LGTM

**Comment by blackboxlogic** [comment]
> LGTM

Could you expand on this thought?

**Comment by juliusfriedman** [comment]
Umm in what way...
LGTM = Looks Good To Me.
Thus it implies I don't see any reason not to take this change...

**Comment by blackboxlogic** [comment]
I was unfamiliar with the acronym, and a search engine brought up a code linter by that name. Thank you for clarifying.

**Pull request merged**
