### PR TITLE
#29 - Added User xml serialization code.

### PR DESCRIPTION
**Pull request by HarelM**
Not very elegant... :-/
Related to #29

### CODE REVIEW

**Comment by xivk** [comment]
Sorry it took so long, merged now! 👍

**Comment by HarelM** [comment]
Will you create a new NuGet package too?

**Comment by xivk** [comment]
One of the tests fails, otherwise that would have already happened automatically... fixing it now.

**Comment by xivk** [comment]
https://www.nuget.org/packages/OsmSharp/6.1.0-pre1

**Comment by HarelM** [comment]
Working great! Thanks!

**Pull request merged**
