### PR TITLE
Add support for gpx_file in OSM v0.6 API classes

### PR DESCRIPTION
**Pull request by HarelM**
Related to issue #33.

### CODE REVIEW

**Comment by HarelM** [comment]
Any updates on this?

**Comment by HarelM** [comment]
@xivk ? Anyone?

**Comment by xivk** [comment]
This is great, sorry for making you wait so long... merging now.

**Comment by xivk** [comment]
@HarelM This is now merged in, had to do some fixes and fix the builds but this should now be available in this package:

https://www.nuget.org/packages/OsmSharp/6.0.0-pre02

**Comment by HarelM** [comment]
Wasn't the previous version was 6.1.0? In any case, I'll try and use it and let you know if everything is OK.

**Comment by xivk** [comment]
Yes, 6.1.0 was a mistake, noticed that only yesterday.

**Pull request merged**
