### PR TITLE
Fixes wrong deserialization of DiffResutls - #54

### PR DESCRIPTION
**Pull request by HarelM**

### CODE REVIEW

**Comment by xivk** [comment]
Wow, you already did this? Did you test with other library reading the compressed files?

**Comment by HarelM** [comment]
I'm still testing this, the resulting file is still too large, I hope I'll find the root cause soon...

**Comment by HarelM** [comment]
@xivk I'm struggling with the compression of the blob's zlib_data member.
I've checked it in so you could have a look at the code I've added:
https://github.com/IsraelHikingMap/core/blob/4dbf5ea304e618441c269cb30aea2a4ab4238975/src/OsmSharp/Streams/PBFOsmStreamTarget.cs#L132
I'm not sure why this causes the read to fail (probably an incorrect write, but I'm not I understand why). 
I've kept a failing test in case you want to see where it fails (`TestReadWriteCompressedRead_ShouldSucceed`).
After compression (although not working correct right now) the file size is as I would expect it to be, so I think this is the last thing that need to be solved in order for the compression to work.

As a side note, I forgot git adds all the commits to the existing pull request - I wanted to create separate  pull request to solve different issues, if you have a way to cherry-pick the first commit is should solve issue #54.

**Comment by HarelM** [comment]
@xivk I've dug deep into zlibstream and I think the implementation currently exists in OSMSharp has a bug or something.
I took a byte array that was created by protobuf and tried to compress it.
It is a 37 long byte array that is getting compressed to 2 bytes (which is obviously not reasonable).
I took the same byte array to a different sample project, added sharpziplib as a reference and compared - it created the right 45 bytes long array.
Here is the array to compress: [examplebytes.txt](https://github.com/OsmSharp/core/files/1978086/examplebytes.txt) in case you want to test it yourself.
I've worked with sharpziplib in my project and I know they support .net core and other profiles.
The problem I'm having with this library is that the portable profile do not match:
```
NU1202: Package SharpZipLib.Portable 0.86.0.3 is not compatible with portable40-net403+sl5+win8+wp8 (.NETPortable,Version=v4.0,Profile=Profile147). Package SharpZipLib.Portable 0.86.0.3 supports: portable-net45+win8+wp8+wpa81 (.NETPortable,Version=v0.0,Profile=Profile259)
NU1202: Package SharpZipLib-WP7 0.86.0.518 is not compatible with portable40-net403+sl5+win8+wp8 (.NETPortable,Version=v4.0,Profile=Profile147). Package SharpZipLib-WP7 0.86.0.518 supports: sl4-wp71 (Silverlight,Version=v4.0,Profile=WindowsPhone71)
```
Making this work will require a lot of changes though (like upgrading to protobuf 2.3.7 etc).
I've removed temporary the PCL compilation and compression is working as expected!
Let me know how you which to proceed.

**Comment by HarelM** [comment]
This PCL thing is extremely annoying... I changed to what seems to be the right profile: portable40-net45+win8+wp8+wpa81 but now it seems like I don't have everything that is required in order to build the solution... :-/
Is it possible to stop supporting PCL?
According to Microsoft this is now deprecated and marked as "Legacy":
https://developercommunity.visualstudio.com/content/problem/161033/vs-2017-1550-community-edition-no-pcl-option-when.html
This, as far as I'm concerned, is the only stopper from completing this feature (allow compression).
@xivk I need your input here.

**Comment by HarelM** [comment]
Some comments I'm not sure what to do with: 
`PBFWriter` is not in use, and does not look like `PBFReader` in terms of symmetry.
I would suggest completely removing `OsmSharp.Ionic.Zlib` and use sharpziplib for all compress and decompress logic.
I don't see a lot of risk with the changes I made in term of backward compatibility etc since compress is an opt-in feature.
If there are any code-review remarks I'll be happy to know.

**Comment by xivk** [comment]
Yes, we can drop PCL netstandard is the thing now, escpecially if that's what's holding you back in finishing this.

I think next version should be *netstandard2.0* only anyway. 

Removing Zlib shouldn't be an issue also. I'll try and review this soon, latest thursday.

**Comment by xivk** [comment]
Sorry this was on my todo list for today but I didn't get to it. Hopefully tomorrow instead.

**Comment by xivk** [comment]
This add a dependency to SharpZipLib and I really really would like to avoid that. It flows into all the projects I use OsmSharp in (and that's a lot of them). Are you absolutely sure we can't do without or include a simple compression/decompression class from somewhere and make it internal?

**Comment by HarelM** [comment]
I've spent 2 days when writing this until I understood there was a bug in the current implementation of deflate. I think it's an extremely bad practice. I can check if system.compression can handle this to remove the dependency but I can't promise. A zip library feels elementary to me... But it might just be me...

**Comment by HarelM** [comment]
Seems like system.compression is not the right solution according to responses here (and a short test I made):
https://stackoverflow.com/questions/37845440/net-deflatestream-vs-linux-zlib-difference
SharpZipLib code can be found here, but it seems like a huge overhead to try and peal off the relevant code:
https://github.com/icsharpcode/SharpZipLib
I think that it's up to you to decide which has a higher priority - adding dependency on sharziplib or trying to add the relevant code.
As a side note, I think that NEST (.Net elasticsearch something) had a similar issue with newton json library and they managed to add this library internally using C# IL hacks that I'm not familiar with (but are possible apparently if they managed to do it).
They have a blog post that hints to it:
https://www.elastic.co/blog/nest-elasticsearch-net-6-0-ga
They are open source too, so there might be a way to see what they did, I haven't took the time to do it though...

**Comment by xivk** [comment]
@HarelM I haven't forgotten about this, I'll get back to it soon!

**Comment by HarelM** [comment]
Let me know if you need any help :-)

**Comment by xivk** [comment]
Thanks @HarelM I did end up including parts to SharpZipLib after all. It was the only solution.

**Pull request merged**
