### PR TITLE
Blackboxlogic issue 80

### PR DESCRIPTION
**Pull request by blackboxlogic**
Re: https://github.com/OsmSharp/core/issues/80

Supporting Xml Deserializing responses from:
GET /api/versions
GET /api/capabilities

### CODE REVIEW

**Comment by xivk** [comment]
This code looks excellent, awaiting feedback in the issue.

**Comment by blackboxlogic** [comment]
I don't expect to be making any more changes in the near future (I got all my tests passing).

**Comment by HarelM** [comment]
@xivk any change to merge this and create a pre-release package so we can in turn create a pre-release package of the OSMApiClient and see if it's doing its job? And by we I mean mostly @blackboxlogic as he's doing most of the heavy lifting :-)

**Comment by xivk** [comment]
@HarelM @blackboxlogic Sorry, I have so much to do at the moment I haven't had the opportunity to look this through. I'll try and do this asap but feel free to ping me again if I didn't manage in the next few days.

**Comment by blackboxlogic** [comment]
This isn't urgent. Get to it when you get to it.

**Comment by xivk** [comment]
This pull request looks good but technically it contains breaking changes. It modifies a few existing public classes and properties. That's fine, we just need to update the version # to v7.

**Comment by xivk** [comment]
No, it's fine, we will just publish v7. There is also the id in the user class that was modified.

**Comment by xivk** [comment]
We can specify the details of the modifications in the release notes, users should know when it's save to update from v6 to v7 that way. Most users won't have an issue anyway with these changes I think.

**Comment by HarelM** [comment]
@xivk Thanks! I agree with your statements.

**Pull request merged**
